theme: jekyll-theme-midnight
title: Today I Learned
Description: This will be a place to post short form content of things I have learned. Topics will mostly focus on DevOps, IaC, Systems Administration, and Systems Engineering but will also include 3d printing, CNC, and Lasers.

This site has been created with github pages.
